


services:

  nginx:
    image: nginx:pedros
    build: ./requirements/nginx/
    container_name: nginx
    env_file:
      - .env.local
    ports:
      - ${NGINX_PORT}:443
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - pedros
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html

  mariadb:
    image: mariadb:pedros
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env.local
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--socket=/var/run/mysqld/mysqld.sock"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - pedros
    volumes:
      - /home/${LOGIN}/data/mariadb:/var/lib/mysql
  
  wordpress:
    image: wordpress:pedros
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env.local
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${WORDPRESS_PORT}"]
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 30s
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - pedros
    volumes:
      - /home/${LOGIN}/data/wordpress:/var/www/html

networks:
  pedros:
    name: pedros