services:

  nginx:
    image: nginx:pedros
    build: ./requirements/nginx/
    container_name: nginx
    env_file:
      - .env
    ports:
      - ${NGINX_PORT}:443
    restart: always
    depends_on:
      wordpress:
        condition: service_healthy
    networks:
      - pedros
    volumes:
      - wordpress:/var/www/html

  mariadb:
    image: mariadb:pedros
    build: ./requirements/mariadb/
    container_name: mariadb
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3306"]
      interval: 10s
      timeout: 10s
      retries: 22
      start_period: 30s
    networks:
      - pedros
    volumes:
      - mariadb:/var/lib/mysql
  
  wordpress:
    image: wordpress:pedros
    build: ./requirements/wordpress/
    container_name: wordpress
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "${WORDPRESS_PORT}"]
      interval: 10s
      timeout: 10s
      retries: 22
      start_period: 30s
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - pedros
    volumes:
      - wordpress:/var/www/html

networks:
  pedros:
    name: pedros



volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${LOGIN}/data/mariadb
